spring:
  application.name: ShareItApp
  main.banner-mode: OFF

  datasource:
    username: "shareit"
    password: "shareit"
    url: "jdbc:postgresql://localhost:6541/shareit"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: info
    org:
      springframework:
        web: info
      hibernate:
        orm:
          jdbc.bind: trace
          jpa.JpaTransactionManager: debug
      transaction: info
      transaction.interceptor: trace
      zalando.logbook: trace # include hibernate.SQL logs