DROP TABLE IF EXISTS users,
                     items,
                     requests;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(300) NOT NULL,
    requestor_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created timestamp without time zone
);

CREATE TABLE IF NOT EXISTS items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(300) NOT NULL,
    is_available boolean NOT NULL,
    owner_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    request_id bigint REFERENCES requests(id)
);

